/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-warm': 'var(--bg-warm)',
        'bg-cream': 'var(--bg-cream)',
        'bg-paper': 'var(--bg-paper)',
        'bg-card': 'var(--bg-card)',
        'bg-card-hover': 'var(--bg-card-hover)',
        'bg-sky': 'var(--bg-sky)',
        'bg-grass': 'var(--bg-grass)',
        'brown-dark': 'var(--brown-dark)',
        'brown-medium': 'var(--brown-medium)',
        'brown-light': 'var(--brown-light)',
        'wood-dark': 'var(--wood-dark)',
        'wood-medium': 'var(--wood-medium)',
        'wood-light': 'var(--wood-light)',
        'accent-orange': 'var(--accent-orange)',
        'accent-coral': 'var(--accent-coral)',
        'accent-peach': 'var(--accent-peach)',
        'accent-cream': 'var(--accent-cream)',
        'accent-lavender': 'var(--accent-lavender)',
        'accent-mint': 'var(--accent-mint)',
        'accent-sky': 'var(--accent-sky)',
        'accent-pink': 'var(--accent-pink)',
        'accent-yellow': 'var(--accent-yellow)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-dim': 'var(--text-dim)',
        'text-light': 'var(--text-light)',
        'border-wood': 'var(--border-wood)',
        'border-light': 'var(--border-light)',
        'border-subtle': 'var(--border-subtle)',
      },
      fontFamily: {
        display: ['ZCOOL KuaiLe', 'sans-serif'],
        pixel: ['"Press Start 2P"', 'monospace'],
        sans: ['Noto Sans SC', 'sans-serif'],
      },
      boxShadow: {
        'soft': 'var(--shadow-soft)',
        'card': 'var(--shadow-card)',
        'button': 'var(--shadow-button)',
        'button-pressed': 'var(--shadow-button-pressed)',
      },
    },
  },
  plugins: [],
}
